### ISSUE TITLE
right usage of SDK

### ISSUE THREAD

**Issue by theahmedy** [shqear93/zoho-inventory-api#10]
`$inventory = new ZohoClient(array('accessToken' =>'access token here','organizationId' =>'org id here'));
`
is this the right usage ?

even it didn't work, does it need any kind of pre-installed softwares ?

**Comment by shqear93** [comment]
According to the documentation it should work
https://www.zoho.com/inventory/api/v1/#organization-id

you only need your curl PHP extension to be installed and enabled on your machine
please read the documentation here :
https://github.com/shqear93/zoho-inventory-api#installation

and make sure to use working access token and org id
