### ISSUE TITLE
Invoice handling. 

### ISSUE THREAD

**Issue by shohag121** [shqear93/zoho-inventory-api#8]
Hi,
Thank you, for the good work but there is no method for handling Invoice.
Is it possible to update the SDK for handling Invoices?

Thanks.

**Comment by shqear93** [comment]
Hi friend,

I stopped working with zoho apis since years ago and I stopped updating my
repo as well.
Unfortunately, many apis are still missing!

If I have time in the next couple of weeks I'll update it Inshallah.

Feel free to fork my repo :)

Regards.
